import {
  BsFillCartFill,
  BsFillHouseDoorFill,
  BsBusFrontFill,
  BsFillLightningFill,
  BsFillMegaphoneFill,
  BsFillPiggyBankFill,
  BsFillUsbDriveFill,
  BsFillTrophyFill,
  BsBarChartFill,
  BsBagFill,
  BsBasket3Fill,
  BsBasket2Fill,
  BsCalculator,
  BsClipboardDataFill,
  BsCoin,
  BsCupHotFill,
  BsDatabaseFill,
  BsHeadphones,
  BsHouseDoor,
  BsInfoCircleFill,
  BsLaptop,
  BsPaletteFill,
  BsPlaystation,
  BsShop,
  BsTwitter,
  BsWindows,
  BsYoutube,
  BsXbox,
} from "react-icons/bs";
import { RiGasStationFill } from "react-icons/ri";
import { MdOutlineAttachMoney } from "react-icons/md";
import {
  AiFillCloud,
  AiFillCar,
  AiFillCreditCard,
  AiFillGift,
  AiFillMedicineBox,
  AiFillSkin,
  AiOutlineBank,
} from "react-icons/ai";
import { CategoryIcon } from "../types/category-icon.types";

export const CategoryIconsMapper = {
  BsFillCartFill: <BsFillCartFill />,
  RiGasStationFill: <RiGasStationFill />,
  MdOutlineAttachMoney: <MdOutlineAttachMoney />,
  AiFillCar: <AiFillCar />,
  AiFillCloud: <AiFillCloud />,
  AiFillCreditCard: <AiFillCreditCard />,
  AiFillGift: <AiFillGift />,
  AiFillMedicineBox: <AiFillMedicineBox />,
  AiFillSkin: <AiFillSkin />,
  AiOutlineBank: <AiOutlineBank />,
  BsFillHouseDoorFill: <BsFillHouseDoorFill />,
  BsBusFrontFill: <BsBusFrontFill />,
  BsFillLightningFill: <BsFillLightningFill />,
  BsFillMegaphoneFill: <BsFillMegaphoneFill />,
  BsFillPiggyBankFill: <BsFillPiggyBankFill />,
  BsFillUsbDriveFill: <BsFillUsbDriveFill />,
  BsFillTrophyFill: <BsFillTrophyFill />,
  BsBarChartFill: <BsBarChartFill />,
  BsBagFill: <BsBagFill />,
  BsBasket3Fill: <BsBasket3Fill />,
  BsBasket2Fill: <BsBasket2Fill />,
  BsCalculator: <BsCalculator />,
  BsClipboardDataFill: <BsClipboardDataFill />,
  BsCoin: <BsCoin />,
  BsCupHotFill: <BsCupHotFill />,
  BsDatabaseFill: <BsDatabaseFill />,
  BsHeadphones: <BsHeadphones />,
  BsHouseDoor: <BsHouseDoor />,
  BsInfoCircleFill: <BsInfoCircleFill />,
  BsLaptop: <BsLaptop />,
  BsPaletteFill: <BsPaletteFill />,
  BsPlaystation: <BsPlaystation />,
  BsShop: <BsShop />,
  BsTwitter: <BsTwitter />,
  BsWindows: <BsWindows />,
  BsYoutube: <BsYoutube />,
  BsXbox: <BsXbox />,
};

export const IconsList: CategoryIcon[] = [
  "BsFillCartFill",
  "RiGasStationFill",
  "AiFillCar",
  "AiFillCloud",
  "AiFillCreditCard",
  "AiFillGift",
  "AiFillMedicineBox",
  "AiFillSkin",
  "AiOutlineBank",
  "BsFillHouseDoorFill",
  "BsBusFrontFill",
  "BsFillLightningFill",
  "BsFillMegaphoneFill",
  "BsFillPiggyBankFill",
  "BsFillUsbDriveFill",
  "BsFillTrophyFill",
  "BsBarChartFill",
  "BsBagFill",
  "BsBasket3Fill",
  "BsBasket2Fill",
  "BsCalculator",
  "BsClipboardDataFill",
  "BsCoin",
  "BsCupHotFill",
  "BsDatabaseFill",
  "BsHeadphones",
  "BsHouseDoor",
  "BsInfoCircleFill",
  "BsLaptop",
  "BsPaletteFill",
  "BsPlaystation",
  "BsShop",
  "BsTwitter",
  "BsWindows",
  "BsYoutube",
  "BsXbox",
];
